import { writable } from "svelte/store";

const data = {
  hsc: {
    full: {
      course: "Full Preparation",
      phx1: [],
      phx2: [],
      chem1: [],
      chem2: [],
      hm2: [],
      hm1: [
        {
          id: "01",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "Full Book",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSdP3hsJw3n_FSgqbt9ZN4vz7bsoMB5UFw3eSsZ4yka5H03GPQ/viewform",
        },
        {
          id: "02",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "1, 2, 3",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSems3TLudUjoU9_BQA2sP86FhVjf031kh1iJzHTriSQuA5UA/viewform",
        },
        {
          id: "03",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "4, 5",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSems3TLudUjoU9_BQA2sP86FhVjf031kh1iJzHTriiSuA5UA/viewform",
        },
        {
          id: "04",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "Chapter - 6, 7",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/FAIpQLSems3TLudUjoU9_BQA2sP86FhVjf031kh1iJzHTriiSQuA5UA/viewform",
        },
        {
          id: "05",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "Full Book",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSes3TLudUjoU9_BQA2sP86FhVjf031kh1iJzHTriiSQuA5UA/viewform",
        },
        {
          id: "06",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "9",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSems3TLudUjoU9_BQA2sP86Fhjf031kh1iJzHTriiSQuA5UA/viewform",
        },
        {
          id: "07",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "Full Book",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSems3TLudUjoU9_BQ2sP86FhVjf031kh1iJzHTriiSQuA5UA/viewform",
        },
        {
          id: "08",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "Full Book",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSemsTLudUjoU9_BQA2sP86FhVjf031kh1iJzHTriiSQuA5UA/viewform",
        },
        {
          id: "09",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "Full Book",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSms3TLudUjoU9_BQA2sP86FhVjf031kh1iJzHTriiSQuA5UA/viewform",
        },
      ],
      zoo: [],
      bot: [],
      coursePath: "full",
    },
    revision: {
      course: "Revision",
      phx1: [],
      phx2: [],
      chem1: [],
      chem2: [],
      hm2: [],
      hm1: [],
      zoo: [],
      bot: [],
      coursePath: "revision",
    },
  },

  admission: {
    EngineeringStandard: {
      course: "Engineering Full Course",
      phx1: [],
      phx2: [],
      chem1: [],
      chem2: [],
      hm2: [],
      hm1: [],
      coursePath: "EngineeringStandard",
    },
    MedicalStandard: {
      course: "Medical Crash Revision",
      phx1: [],
      phx2: [],
      chem1: [],
      chem2: [],
      zoo: [],
      bot: [],
      coursePath: "MedicalStandard",
    },

    VarsityStandard: {
      course: "Varsity Standard",
      phx1: [],
      phx2: [],
      chem1: [],
      chem2: [],
      zoo: [],
      bot: [],
      hm2: [],
      hm1: [
        {
          id: "01",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "Full Book",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSdP3hsJw3n_FSgqbt9ZN4vz7bsoMB5UFw3eSsZ4yka5H03GPQ/viewform",
        },
        {
          id: "02",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "1, 2, 3",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSems3TLudUjoU9_BQA2sP86FhVjf031kh1iJzHTriSQuA5UA/viewform",
        },
        {
          id: "03",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "4, 5",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSems3TLudUjoU9_BQA2sP86FhVjf031kh1iJzHTriiSuA5UA/viewform",
        },
        {
          id: "04",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "Chapter - 6, 7",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/FAIpQLSems3TLudUjoU9_BQA2sP86FhVjf031kh1iJzHTriiSQuA5UA/viewform",
        },
        {
          id: "05",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "Full Book",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSes3TLudUjoU9_BQA2sP86FhVjf031kh1iJzHTriiSQuA5UA/viewform",
        },
        {
          id: "06",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "9",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSems3TLudUjoU9_BQA2sP86Fhjf031kh1iJzHTriiSQuA5UA/viewform",
        },
        {
          id: "07",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "Full Book",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSems3TLudUjoU9_BQ2sP86FhVjf031kh1iJzHTriiSQuA5UA/viewform",
        },
        {
          id: "08",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "Full Book",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSemsTLudUjoU9_BQA2sP86FhVjf031kh1iJzHTriiSQuA5UA/viewform",
        },
        {
          id: "09",
          subject: "Higher Math 1st Paper",
          exam: "Paper Final",
          type: "MCQ",
          marks: 50,
          syllabus: "Full Book",
          time: "30 mins",
          link: "https://docs.google.com/forms/d/e/1FAIpQLSms3TLudUjoU9_BQA2sP86FhVjf031kh1iJzHTriiSQuA5UA/viewform",
        },
      ],
      coursePath: "VarsityStandard",
    },
    DUSpecial: {
      course: "DU Special",
      phx1: [],
      phx2: [],
      chem1: [],
      chem2: [],
      hm2: [],
      hm1: [],
      zoo: [],
      bot: [],
      coursePath: "DUSpecial",
    },
  },
};

const store = writable(data);

export default store;
